services:
  postgres:
    image: ankane/pgvector:latest
    container_name: acua-core-postgres
    restart: always
    environment:
      POSTGRES_USER: acuacore_user
      POSTGRES_PASSWORD: acuacore_pass
      POSTGRES_DB: acuacore_vectors
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pitaya_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: acua-core-api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3014:3014"
    networks:
      - pitaya_net
    depends_on:
      - postgres

networks:
  pitaya_net:
    external: true

volumes:
  postgres_data:
